wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,6 +9,8 @@ env:
   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
   SLACK_DEFAULT_CHANNEL_ID: ${{ secrets.SLACK_DEFAULT_CHANNEL_ID }}
   DENO_DIR: .deno_cache
+  tests: "passed"
+  benchmarks: "passed"
 
 jobs:
   build:
@@ -29,23 +31,33 @@ jobs:
 
       - name: Run tests
         id: run_tests
-        run: |
-          deno task test
+        run: deno task test || echo "tests=failed" >> $GITHUB_ENV
 
       - name: Run benchmarks
         id: run_benchmarks
-        run: |
-          deno task bench
+        run: deno task bench || echo "benchmarks=failed" >> $GITHUB_ENV
 
-      - name: Tag as 'latest' and push tag
+      - name: Increment version and push tag
         run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
-          git tag -f latest  # Force update the 'latest' tag to the latest commit
-          git push origin latest --force  # Force push the 'latest' tag
-          echo "### Latest Tag" >> $GITHUB_STEP_SUMMARY
-          echo "The tag has been updated to 'latest'." >> $GITHUB_STEP_SUMMARY
+          git fetch --tags
+          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
+          IFS='.' read -r -a version_parts <<< "$latest_tag"
+          major="${version_parts[0]}"
+          minor="${version_parts[1]}"
+          new_minor=$((minor + 1))
+          new_version="$major.$new_minor"
+          echo "new_version=$new_version" >> $GITHUB_ENV
+          git tag "$new_version"
+          git push origin "$new_version"
 
-      - name: Send POST request
+      - name: Send POST request to Slack
         run: |
-          curl -X POST "https://coa-utils.deno.dev/${{ secrets.URL_PATH_KEY }}/slack/coa_utils" -d '{}'
+          curl -X POST "https://coa-utils.deno.dev/${{ secrets.URL_PATH_KEY }}/slack/coa_utils" \
+          -H "Content-Type: application/json" \
+          -d "{
+              \"tests\": \"${{ env.tests }}\",
+              \"benchmarks\": \"${{ env.benchmarks }}\",
+              \"latest\": \"${{ env.new_version }}\"
+          }"
